<?php
$codigo_paciente = isset($_POST["codigo_paciente"])?$_POST["codigo_paciente"]:null;
$codigo_internacao = isset($_POST["codigo_internacao"])?$_POST["codigo_internacao"]:null;
$has_cronica = isset($_POST["has_cronica"])?$_POST["has_cronica"]:0;
$has_gestacional = isset($_POST["has_gestacional"])?$_POST["has_gestacional"]:0;
$dp_tipo = isset($_POST["db_tipo"])?$_POST["db_tipo"]:0;
$db_gestacional = isset($_POST["db_gestacional"])?$_POST["db_gestacional"]:0;
$dlp = isset($_POST["dlp"])?$_POST["dlp"]:0;
$outros = isset($_POST["outros"])?$_POST["outros"]:"";
$fi = isset($_POST["fi"])?$_POST["fi"]:"";
$altura = isset($_POST["altura"])?$_POST["altura"]:"";
$idade_gestacional = isset($_POST["idade_gestacional"])?$_POST["idade_gestacional"]:"";
$em = isset($_POST["em"])?$_POST["em"]:"";
$peso_pg = isset($_POST["peso_pg"])?$_POST["peso_pg"]:"";
$imc_pg = isset($_POST["imc_pg"])?$_POST["imc_pg"]:"";
$tipo_obesidade_gestacional = isset($_POST["tipo_obesidade_gestacional"])?$_POST["tipo_obesidade_gestacional"]:"";
$peso_atual = isset($_POST["peso_atual"])?$_POST["peso_atual"]:"";
$imc_atual = isset($_POST["imc_atual"])?$_POST["imc_atual"]:"";
$tipo_obesidade_atual = isset($_POST["tipo_obesidade_atual"])?$_POST["tipo_obesidade_atual"]:"";
$gestante = isset($_POST["gestante"])?$_POST["gestante"]:"";
$ganho_peso = isset($_POST["ganho_peso"])?$_POST["ganho_peso"]:"";
$alergia_gluten = isset($_POST["alergia_gluten"])?$_POST["alergia_gluten"]:0;
$alergia_lactose = isset($_POST["alergia_lactose"])?$_POST["alergia_lactose"]:0;
$alergia_proteina_leite = isset($_POST["alergia_proteina_leite"])?$_POST["alergia_proteina_leite"]:0;
$alergia_corante = isset($_POST["alergia_corante"])?$_POST["alergia_corante"]:0;
$alergia_ovo = isset($_POST["alergia_ovo"])?$_POST["alergia_ovo"]:0;
$alergia_amendoim = isset($_POST["alergia_amendoim"])?$_POST["alergia_amendoim"]:0;
$alergia_frutos_mar = isset($_POST["alergia_frutos_mar"])?$_POST["alergia_frutos_mar"]:0;
$alergia_conservantes = isset($_POST["alergia_conservantes"])?$_POST["alergia_conservantes"]:0;
$outros_alergia = isset($_POST["outros_alergia"])?$_POST["outros_alergia"]:"";
$preferencia_carne_bovina = isset($_POST["preferencia_carne_bovina"])?$_POST["preferencia_carne_bovina"]:0;
$preferencia_frango = isset($_POST["preferencia_frango"])?$_POST["preferencia_frango"]:0;
$preferencia_peixe = isset($_POST["preferencia_peixe"])?$_POST["preferencia_peixe"]:0;
$preferencia_ovo = isset($_POST["preferencia_ovo"])?$_POST["preferencia_ovo"]:0;
$preferencia_vegano = isset($_POST["preferencia_vegano"])?$_POST["preferencia_vegano"]:0;
$preferencia_ovo_lacto_vegetariano = isset($_POST["preferencia_ovo_lacto_vegetariano"])?$_POST["preferencia_ovo_lacto_vegetariano"]:0;
$preferencia_sopa = isset($_POST["preferencia_sopa"])?$_POST["preferencia_sopa"]:"";
$sopa = isset($_POST["sopa"])?$_POST["sopa"]:0;
$refeicao = isset($_POST["refeicao"])?$_POST["refeicao"]:0;
$acucar = isset($_POST["acucar"])?$_POST["acucar"]:0;
$adocante_aspartame = isset($_POST["adocante_aspartame"])?$_POST["adocante_aspartame"]:0;
$adocante_sucralose = isset($_POST["adocante_sucralose"])?$_POST["adocante_sucralose"]:0;
$verduras = isset($_POST["verduras"])?$_POST["verduras"]:"";
$legumes = isset($_POST["legumes"])?$_POST["legumes"]:"";
$frutas = isset($_POST["frutas"])?$_POST["frutas"]:"";
$leite_derivados = isset($_POST["leite_derivados"])?$_POST["leite_derivados"]:"";
$cereais = isset($_POST["cereais"])?$_POST["cereais"]:"";
$leguminosas = isset($_POST["leguminosas"])?$_POST["leguminosas"]:"";
$creme_milho = isset($_POST["creme_milho"])?$_POST["creme_milho"]:0;
$creme_palmito = isset($_POST["creme_palmito"])?$_POST["creme_palmito"]:0;
$cha = isset($_POST["cha"])?$_POST["cha"]:0;
$agua_coco = isset($_POST["agua_coco"])?$_POST["agua_coco"]:0;
$iogurte_comum = isset($_POST["iogurte_comum"])?$_POST["iogurte_comum"]:0;
$iogurte_desnatado = isset($_POST["iogurte_desnatado"])?$_POST["iogurte_desnatado"]:0;
$observacao = isset($_POST["observacao"])?$_POST["observacao"]:"";
$sugo = isset($_POST["sugo"])?$_POST["sugo"]:0;
$ervas_finas = isset($_POST["ervas_finas"])?$_POST["ervas_finas"]:0;
$branco = isset($_POST["branco"])?$_POST["branco"]:0;
$champignon = isset($_POST["champignon"])?$_POST["champignon"]:0;
$alcaparras = isset($_POST["alcaparras"])?$_POST["alcaparras"]:0;
$madeira = isset($_POST["madeira"])?$_POST["madeira"]:0;
$observacao_molhos = isset($_POST["observacao_molhos"])?$_POST["observacao_molhos"]:"";
$acerola_mamao = isset($_POST["acerola_mamao"])?$_POST["acerola_mamao"]:0;
$abacaxi = isset($_POST["abacaxi"])?$_POST["abacaxi"]:0;
$caju = isset($_POST["caju"])?$_POST["caju"]:0;
$manga = isset($_POST["manga"])?$_POST["manga"]:0;
$uva = isset($_POST["uva"])?$_POST["uva"]:0;
$maracuja = isset($_POST["maracuja"])?$_POST["maracuja"]:0;
$morango = isset($_POST["morango"])?$_POST["morango"]:0;
$pessego = isset($_POST["pessego"])?$_POST["pessego"]:0;
$laranja_mamao = isset($_POST["laranja_mamao"])?$_POST["laranja_mamao"]:0;
$melancia = isset($_POST["melancia"])?$_POST["melancia"]:0;
$historico_evolucao_nutricional = isset($_POST["historico_evolucao_nutricional"])?$_POST["historico_evolucao_nutricional"]:"";

echo ("<br />");
echo "codigo_paciente: ". $codigo_paciente;
echo ("<br />");
echo "codigo_internacao: " .$codigo_internacao;
echo ("<br />");
echo "has_cronica: " .$has_cronica;
echo ("<br />");
echo "has_gestacional: " .$has_gestacional;
echo ("<br />");
echo "dp_tipo: " .$dp_tipo;
echo ("<br />");
echo "db_gestacional: " .$db_gestacional;
echo ("<br />");
echo "dlp: " .$dlp;
echo ("<br />");
echo "outros: " .$outros;
echo ("<br />");
echo "fi: " .$fi;
echo ("<br />");
echo "altura: " .$altura;
echo ("<br />");
echo "idade_gestacional: " .$idade_gestacional;
echo ("<br />");
echo "em: " .$em;
echo ("<br />");
echo "peso_pg: " .$peso_pg;
echo ("<br />");
echo "imc_pg: " .$imc_pg;
echo ("<br />");
echo "tipo_obesidade_gestacional: " .$tipo_obesidade_gestacional;
echo ("<br />");
echo "peso_atual: " .$peso_atual;
echo ("<br />");
echo "imc_atual: " .$imc_atual;
echo ("<br />");
echo "tipo_obesidade_atual: " .$tipo_obesidade_atual;
echo ("<br />");
echo "gestante: " .$gestante;
echo ("<br />");
echo "ganho_peso: " .$ganho_peso;
echo ("<br />");
echo "alergia_gluten: " .$alergia_gluten;
echo ("<br />");
echo "alergia_lactose: " .$alergia_lactose;
echo ("<br />");
echo "alergia_proteina_leite: " .$alergia_proteina_leite;
echo ("<br />");
echo "alergia_corante: " .$alergia_corante;
echo ("<br />");
echo "alergia_ovo: " .$alergia_ovo;
echo ("<br />");
echo "alergia_amendoim: " .$alergia_amendoim;
echo ("<br />");
echo "alergia_frutos_mar: " .$alergia_frutos_mar;
echo ("<br />");
echo "alergia_conservantes: " .$alergia_conservantes;
echo ("<br />");
echo "outros_alergia: " .$outros_alergia;
echo ("<br />");
echo "preferencia_carne_bovina: " .$preferencia_carne_bovina;
echo ("<br />");
echo "preferencia_frango: " .$preferencia_frango;
echo ("<br />");
echo "preferencia_peixe: " .$preferencia_peixe;
echo ("<br />");
echo "preferencia_ovo: " .$preferencia_ovo;
echo ("<br />");
echo "preferencia_vegano: " .$preferencia_vegano;
echo ("<br />");
echo "preferencia_ovo_lacto_vegetariano: " .$preferencia_ovo_lacto_vegetariano;
echo ("<br />");
echo "preferencia_sopa: " .$preferencia_sopa;
echo ("<br />");
echo "sopa: " .$sopa;
echo ("<br />");
echo "refeicao: " .$refeicao;
echo ("<br />");
echo "acucar: " .$acucar;
echo ("<br />");
echo "adocante_aspartame: " .$adocante_aspartame;
echo ("<br />");
echo "adocante_sucralose: " .$adocante_sucralose;
echo ("<br />");
echo "verduras: " .$verduras;
echo ("<br />");
echo "legumes: " .$legumes;
echo ("<br />");
echo "frutas: " .$frutas;
echo ("<br />");
echo "leite_derivados: " .$leite_derivados;
echo ("<br />");
echo "cereais: " .$cereais;
echo ("<br />");
echo "leguminosas: " .$leguminosas;
echo ("<br />");
echo "creme_milho: " .$creme_milho;
echo ("<br />");
echo "creme_palmito: " .$creme_palmito;
echo ("<br />");
echo "cha: " .$cha;
echo ("<br />");
echo "agua_coco: " .$agua_coco;
echo ("<br />");
echo "iogurte_comum: " .$iogurte_comum;
echo ("<br />");
echo "iogurte_desnatado: " .$iogurte_desnatado;
echo ("<br />");
echo "observacao: " .$observacao;
echo ("<br />");
echo "sugo: " .$sugo;
echo ("<br />");
echo "ervas_finas: " .$ervas_finas;
echo ("<br />");
echo "branco: " .$branco;
echo ("<br />");
echo "champignon: " .$champignon;
echo ("<br />");
echo "alcaparras: " .$alcaparras;
echo ("<br />");
echo "madeira: " .$madeira;
echo ("<br />");
echo "observacao_molhos: " .$observacao_molhos;
echo ("<br />");
echo "acerola_mamao: " .$acerola_mamao;
echo ("<br />");
echo "abacaxi: " .$abacaxi;
echo ("<br />");
echo "caju: " .$caju;
echo ("<br />");
echo "manga: " .$manga;
echo ("<br />");
echo "uva: " .$uva;
echo ("<br />");
echo "maracuja: " .$maracuja;
echo ("<br />");
echo "morango: " .$morango;
echo ("<br />");
echo "pessego: " .$pessego;
echo ("<br />");
echo "laranja_mamao: " .$laranja_mamao;
echo ("<br />");
echo "melancia: " .$melancia;
echo ("<br />");
echo "historico_evolucao_nutricional: " .$historico_evolucao_nutricional;


?>